# docker-compose.yml
version: '3.8'
services:
  backend:
    env_file:
      - .env
    build: ./webscrapper
    ports:
      - ${BACKEND_PORT}
    volumes:
      - ./webscrapper:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${BACKEND_PORT}
    networks:
      default:
        aliases:
            - backend

  streamlit-app:
    env_file:
      - .env
    build: ./front
    container_name: streamlitapp
    depends_on:
      - backend 
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    working_dir: /usr/src/app
  