# docker-compose.yml
version: '3.8'
services:
  backend:
    env_file:
      - .env
    build: ./webscrapper
    ports:
      - ${BACKEND_PORT}
    volumes:
      - ./webscrapper:/app
    healthcheck:
      test: curl --fail http://localhost:${BACKEND_PORT} || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${BACKEND_PORT}
    networks:
      default:
        aliases:
            - backend

  streamlit-app:
    env_file:
      - .env
    build: ./front
    container_name: streamlitapp
    depends_on:
      - backend 
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    working_dir: /usr/src/app
    healthcheck:
      test: curl --fail http://localhost:${BACKEND_PORT} || exit 1 
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  