# docker-compose.yml
version: '3.8'
networks: 
  monitoring: 
    driver: bridge 

# Persist data from Prometheus and Grafana with Docker volumes
volumes: 
  prometheus_data: {}
  grafana_data: {}

services:
  
  backend:
    env_file:
      - .env
    build: ./webscrapper
    ports:
      - 5000:5000
    volumes:
      - ./webscrapper:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    networks:
      monitoring:
        aliases:
          - backend

  streamlit-app:
    env_file:
      - .env
    build: ./front
    container_name: streamlitapp
    depends_on:
      - backend 
    ports:
      - 8501:8501
    working_dir: /usr/src/app
    networks:
      - monitoring